name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build and push Docker images
      run: |
        docker build -t ghcr.io/${{ github.repository }}/service1:latest ./service1
        docker build -t ghcr.io/${{ github.repository }}/service2:latest ./service2
        docker push ghcr.io/${{ github.repository }}/service1:latest
        docker push ghcr.io/${{ github.repository }}/service2:latest

