name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    
    - name: Build and push Docker images
      run: |
        # Convert repository name to lowercase
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        # Build and push the application image
        docker build -t ghcr.io/${REPO_NAME}:millio-v1 ./task-infra
        docker push ghcr.io/${REPO_NAME}:millio-v1
        
        # Push the PostgreSQL image (no need to build as it's an official image)
        docker pull postgres:16
        docker tag postgres:16 ghcr.io/${REPO_NAME}:millio-db
        docker push ghcr.io/${REPO_NAME}:millio-db
    
    - name: Update registry-compose.yaml
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        cp ./task-infra/compose.yaml ./task-infra/registry-compose.yaml
        sed -i 's|build:|image: ghcr.io/'${REPO_NAME}':millio-v1|' ./task-infra/registry-compose.yaml
        sed -i 's|image: postgres:16|image: ghcr.io/'${REPO_NAME}':millio-db|' ./task-infra/registry-compose.yaml
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./task-infra/registry-compose.yaml
        git commit -m "Add registry-compose.yaml with registry image references" || echo "No changes to commit"
        git push
