name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    
    - name: Build and push Docker images
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      run: |
        # Convert repository name to lowercase
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        # Find the Dockerfile
        DOCKERFILE_PATH=$(find ./task-infra -name Dockerfile -o -name dockerfile)
        if [ -z "$DOCKERFILE_PATH" ]; then
          echo "Dockerfile not found in task-infra directory or its subdirectories"
          exit 1
        fi
        
        # Extract the directory containing the Dockerfile
        DOCKER_CONTEXT=$(dirname "$DOCKERFILE_PATH")
        
        # Build and push the application image
        docker build -t ghcr.io/${REPO_NAME}:millio-v1 -f "$DOCKERFILE_PATH" "$DOCKER_CONTEXT"
        docker push ghcr.io/${REPO_NAME}:millio-v1
        
        # Push the PostgreSQL image (no need to build as it's an official image)
        docker pull postgres:16
        docker tag postgres:16 ghcr.io/${REPO_NAME}:millio-db
        docker push ghcr.io/${REPO_NAME}:millio-db

    - name: Update registry-compose.yaml
      run: |
        if [ ! -f ./task-infra/registry-compose.yaml ]; then
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          cp ./task-infra/compose.yaml ./task-infra/registry-compose.yaml
          sed -i 's|build:|image: ghcr.io/'${REPO_NAME}':millio-v1|' ./task-infra/registry-compose.yaml
          sed -i 's|image: postgres:16|image: ghcr.io/'${REPO_NAME}':millio-db|' ./task-infra/registry-compose.yaml
        fi

    - name: Commit and push changes if registry-compose.yaml was created
      run: |
        if [ -n "$(git status --porcelain ./task-infra/registry-compose.yaml)" ]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./task-infra/registry-compose.yaml
          git commit -m "Create registry-compose.yaml with image references"
          git push
        else
          echo "registry-compose.yaml already exists and is up to date"
        fi

    - name: Debug Railway Token and Project ID
      run: |
        if [ -n "$RAILWAY_TOKEN" ]; then
          echo "RAILWAY_TOKEN is set (value hidden)"
        else
          echo "RAILWAY_TOKEN is not set"
        fi
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

   
    - name: Install Render CLI via npm
      run: |
        npm install render-cli -g
        echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
      shell: bash

    - name: Deploy Application Image to Render
      run: |
        render services update srv-crl0esogph6c73anil0g \
          --docker-image ghcr.io/${{ github.repository }}:millio-v1 \
          --env SPRING_DATA_SOURCE_URL=jdbc:postgresql://${{ secrets.RENDER_POSTGRES_HOST }}:5432/${{ secrets.POSTGRES_DB }} \
          --env SPRING_DATA_SOURCE_USERNAME=${{ secrets.POSTGRES_USER }} \
          --env SPRING_DATA_SOURCE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

    - name: Deploy PostgreSQL Image to Render
      run: |
        render services update dpg-crl0hgrqf0us73cmfm7g-a \
          --docker-image ghcr.io/${{ github.repository }}:millio-db
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
