name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    
    - name: Build and push Docker images
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      run: |
        # Convert repository name to lowercase
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        # Find the Dockerfile
        DOCKERFILE_PATH=$(find ./task-infra -name Dockerfile -o -name dockerfile)
        if [ -z "$DOCKERFILE_PATH" ]; then
          echo "Dockerfile not found in task-infra directory or its subdirectories"
          exit 1
        fi
        
        # Extract the directory containing the Dockerfile
        DOCKER_CONTEXT=$(dirname "$DOCKERFILE_PATH")
        
        # Build and push the application image
        docker build -t ghcr.io/${REPO_NAME}:millio-v1 -f "$DOCKERFILE_PATH" "$DOCKER_CONTEXT"
        docker push ghcr.io/${REPO_NAME}:millio-v1
        
        # Push the PostgreSQL image (no need to build as it's an official image)
        docker pull postgres:16
        docker tag postgres:16 ghcr.io/${REPO_NAME}:millio-db
        docker push ghcr.io/${REPO_NAME}:millio-db

    - name: Update registry-compose.yaml
      run: |
        if [ ! -f ./task-infra/registry-compose.yaml ]; then
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          cp ./task-infra/compose.yaml ./task-infra/registry-compose.yaml
          sed -i 's|build:|image: ghcr.io/'${REPO_NAME}':millio-v1|' ./task-infra/registry-compose.yaml
          sed -i 's|image: postgres:16|image: ghcr.io/'${REPO_NAME}':millio-db|' ./task-infra/registry-compose.yaml
        fi

    - name: Commit and push changes if registry-compose.yaml was created
      run: |
        if [ -n "$(git status --porcelain ./task-infra/registry-compose.yaml)" ]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./task-infra/registry-compose.yaml
          git commit -m "Create registry-compose.yaml with image references"
          git push
        else
          echo "registry-compose.yaml already exists and is up to date"
        fi

    - name: Debug Railway Token and Project ID
      run: |
        if [ -n "$RAILWAY_TOKEN" ]; then
          echo "RAILWAY_TOKEN is set (value hidden)"
        else
          echo "RAILWAY_TOKEN is not set"
        fi
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Install Railwayc
      run: npm i -g @railway/cli

    - name: Deploy to Railway
      run: |
        railway up --detach --service app --file ./task-infra/registry-compose.yaml
        railway up --detach --service postgres_db --file ./task-infra/registry-compose.yaml
      env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}